# Generated by Django 5.2.1 on 2025-05-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_date', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('cover_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
